language: generic
sudo: required

services:
  - docker

before_install:
  - docker pull greenaddress/walletcrx

script: docker run -v $PWD:/walletcrx greenaddress/walletcrx /bin/sh -c "cd /walletcrx && ./makePackages.sh -b master"
